### ISSUE TITLE
Update to-fix without a geojson files

### ISSUE THREAD

**Issue by Rub21** [osmlab/to-fix#207]
to-fix-backend support update without a file , some time is necessary update a comment o description in the task.

![image](https://cloud.githubusercontent.com/assets/1152236/25724587/17a911e6-30e2-11e7-9dd9-7b35c982aeaf.png)

using  to-fix-cli I can update
![image](https://cloud.githubusercontent.com/assets/1152236/25724621/35cede76-30e2-11e7-9ecc-dd9f006357f2.png)

**Comment by maning** [comment]
Bump.  I have the same issue with web-based update:
![screen shot 2017-05-06 at 18 57 51](https://cloud.githubusercontent.com/assets/353700/25772690/208b7f30-328e-11e7-9574-691a53a094c1.png)

**Comment by maning** [comment]
@Rub21 not working for me in cli:

```
maning@hjutoe ~/projects/git/tofix-cli (master)*$ tfcli production update --idtask crossingbuildinginthephilippines --name 'Crossing building in the Philippines' --comment 'Fixed crossing/overlapping buildings. https://github.com/OSMPH/papercut_fix/issues/13'
UPDATE TASK :https://build-to-fix-production.mapbox.com/tasks
/Users/maning/projects/git/tofix-cli/node_modules/form-data/lib/form_data.js:217
  var filename = options.filename || value.name || value.path;
                                          ^

TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (/Users/maning/projects/git/tofix-cli/node_modules/form-data/lib/form_data.js:217:43)
    at FormData._multiPartHeader (/Users/maning/projects/git/tofix-cli/node_modules/form-data/lib/form_data.js:171:33)
    at FormData.append (/Users/maning/projects/git/tofix-cli/node_modules/form-data/lib/form_data.js:64:21)
    at appendFormValue (/Users/maning/projects/git/tofix-cli/node_modules/request/request.js:326:21)
    at Request.init (/Users/maning/projects/git/tofix-cli/node_modules/request/request.js:337:11)
    at new Request (/Users/maning/projects/git/tofix-cli/node_modules/request/request.js:130:8)
    at request (/Users/maning/projects/git/tofix-cli/node_modules/request/index.js:54:10)
    at Function.put (/Users/maning/projects/git/tofix-cli/node_modules/request/index.js:62:12)
    at Object.module.exports.update (/Users/maning/projects/git/tofix-cli/src/crudTask.js:46:13)
    at Object.<anonymous> (/Users/maning/projects/git/tofix-cli/index.js:24:16)

```

**Comment by Rub21** [comment]
@maning before run `tfcli` you should export your to-fix token `export token="xxx"` and then 

`tfcli production update --idtask crossingbuildinginthephilippines --name  'Crossing building in the Philippines' --comment 'Fixed crossing/overlapping buildings. https://github.com/OSMPH/papercut_fix/issues/13' --description 'xxxx' --file <path/to/file>`
